languageCode = "en-us"
baseURL = "https://www.onitato.com/"
title = "Linuturk's Natter"
author = "Justin Phelps"
copyright = "&copy; 2022. All rights reserved."
theme = "blackburn"
canonifyurls = true
paginate = 5

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown on the home page
  # subtitle = ""
  brand = "Onitato"
  googleAnalytics = "G-ERZFV9WYV6"
  disqus = "linuturksnatter"
  # CSS name for highlight.js
  highlightjs = "default"
  highlightjs_extra_languages = ["yaml", "Dockerfile"]
  dateFormat = "Jan 02 2006, 15:04"
  # Include any custom CSS and/or JS files
  # (relative to /static folder)
  #custom_css = ["css/my.css"]
  #custom_js = ["js/my.js"]

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    identifier = "home"
    url = "/"
  [[menu.main]]
    name = "Posts"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 2
    identifier = "post"
    url = "/post/"
  [[menu.main]]
    name = "Topics"
    pre = "<i class='fa fa-folder fa-fw'></i>"
    weight = 3
    identifier = "topic"
    url = "/topics/"
  [[menu.main]]
    name = "Tags"
    pre = "<i class='fa fa-tags fa-fw'></i>"
    weight = 4
    identifier = "tag"
    url = "/tags/"
  [[menu.main]]
    name = "About"
    pre = "<i class='fa fa-user fa-fw'></i>"
    weight = 5
    identifier = "about"
    url = "/about/"
  [[menu.main]]
    name = "Gaming"
    pre = "<i class='fa fa-gamepad fa-fw'></i>"
    weight = 6
    identifier = "gaming"
    url = "/gaming/"
  [[menu.main]]
    name = "Nextcloud"
    pre = "<i class='fa fa-cloud fa-fw'></i>"
    weight = 7
    identifier = "nextcloud"
    url = "https://nextcloud.com/sharing#linuturk@nextcloud.onitato.com"
  [[menu.main]]
    name = "Report Bug"
    pre = "<i class='fa fa-bug fa-fw'></i>"
    weight = 8
    identifier = "bug"
    url = "https://github.com/Linuturk/www.onitato.com/issues"
  [[menu.main]]
    name = "Donate"
    pre = "<i class='fa fa-btc fa-fw'></i>"
    weight = 9
    identifier = "bitcoin"
    url = "bitcoin:1FkKq8MSLuBMcE6NfvZ4qLhAYK6auTthTM"

[social]
  # Link your social networking accounts to the side menu
  # by entering your username or ID.
  twitter = "Linuturk"
  facebook = "linuturk"
  youtube = "Linuturk"
  linkedin = "linuturk"
  reddit = "Linuturk"
  github = "linuturk"
  steam = "linuturk"
  keybase = "linuturk"
