languageCode = "en-us"
baseURL = "https://www.onitato.com/"
title = "Linuturk's Natter"
author = "Justin Phelps"
copyright = "&copy; 2023. All rights reserved."
theme = "nightfall"
canonifyurls = true
paginate = 5
uglyURLs = true

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  author = "Justin Phelps"
  user = "linuturk"
  hostname = "onitato.com"
  googleAnalytics = "G-ERZFV9WYV6"
  disqus = "linuturksnatter"
  highlightjs = "default"
  highlightjs_extra_languages = ["yaml", "Dockerfile"]
  dateFormat = "Jan 02 2006, 15:04"

[menu]
  # Shown in the side menu.
  [[menu.header]]
    name = "Posts"
    weight = 1
    url = "/post.html"
  [[menu.header]]
    name = "Topics"
    weight = 2
    url = "/topics.html"
  [[menu.header]]
    name = "Tags"
    weight = 3
    url = "/tags.html"
  [[menu.header]]
    name = "Gaming"
    weight = 4
    url = "/gaming.html"
  [[menu.header]]
    name = "About"
    weight = 5
    url = "/about.html"

[[params.social]]
  key = 0
  name = mastodon
  url = "https://toot.onitato.com/@linuturk"

[[params.social]]
  key = 1
  name = github
  url = "https://github.com/linuturk"

[[params.social]]
  key = 2
  name = linkedin
  url = "https://linkedin.com/in/linuturk"
