#!/bin/bash

FILES=$@
WORDS="./.wordlist"
FOUND=false

spellcheck ()
{
	FILE=$1
	cat $1 | aspell list --extra-dicts=$WORDS
}
for i in $FILES
do
	if [[ $(spellcheck $i) ]]
	then
		echo "Checking: $i"
		spellcheck $i
		FOUND=true
	fi
done

if $FOUND
then
	exit 1
fi
