#!/bin/bash

FILES=$@
WORDS="./.wordlist"

for i in $FILES
do
	if [[ $(cat $i | aspell list --extra-dicts=$WORDS) ]]; then
		echo "Checking: $i"
		cat $i | aspell list --extra-dicts=$WORDS
		EXIT=1
	else
		EXIT=0
	fi
done
exit $EXIT
