name: build-and-deploy

on: [push]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.S3_DEPLOY_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_DEPLOY_SECRET_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.ONITATO_BUCKET_REGION }}

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Submodule
        run: make submodule-init
      - name: Dependencies
        run: make deps
      - name: Spellcheck
        run: make spell
      - name: Build
        run: make build
      - name: Deploy
        run: aws s3 sync ${{ gitea.workspace }}/public/ s3://${{ secrets.ONITATO_BUCKET }} --delete