workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
        requires:
          - build
        filters:
          branches:
            only: master
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run: sudo apt install -y aspell
      - run: bash spell content/post/*
      - run: bash ./install-hugo.sh
      - run: hugo --cleanDestinationDir
  deploy:
    docker:
      - image: circleci/python
    steps:
      - run: sudo pip install awscli
      - run: aws s3 sync $HOME/$CIRCLE_PROJECT_REPONAME/public s3://$BUCKET --delete