version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: sudo apt install -y aspell
      - run: bash spell content/post/*
      - run: bash ./install-hugo.sh
      - run: hugo env
      - run: hugo check
      - run: hugo config
      - run: hugo -v --cleanDestinationDir
      - persist_to_workspace:
          root: .
          paths:
            - public
  deploy:
    docker:
      - image: circleci/python
    steps:
      - run: sudo pip install awscli
      - attach_workspace:
          at: workspace
      - run: aws s3 sync workspace/public/ s3://$BUCKET --delete
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master