version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.19.2
    steps:
      - checkout
      - run: make ci
      - persist_to_workspace:
          root: .
          paths:
            - public
  deploy:
    docker:
      - image: circleci/python
    steps:
      - run: sudo pip install awscli
      - attach_workspace:
          at: workspace
      - run: make sync
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master